### ISSUE TITLE
Zero configuration installation with Docker Compose

### ISSUE THREAD

**Issue by pe3** [vrk-kpa/xroad-public#9]
Should the [installation instructions](https://github.com/vrk-kpa/xroad-public/blob/master/ansible/README.md) work on a laptop? I doubt I can get and configure "fully qualified host names" on my machine as instructed.

With Docker Compose host names could be configured in the `docker-compose.yml` file. The following file sets up two servers with the domain names `db` and `php`:

```
version: '2'
services:
  db:
    image: k0st/alpine-mariadb
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
  php:
    build: "./app-server"
    depends_on:
      - db
    volumes:
      - "./app:/www"
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      APP_DB_HOST: db
      APP_DB_NAME: mydb
      APP_DB_USER: myuser
      APP_DB_PASSWORD: mypass
```
